apply shfmt

diff --git a/android/android_utils b/android/android_utils
--- a/android/android_utils
+++ b/android/android_utils
@@ -1,7 +1,7 @@
 #!/bin/zsh
 
-# This file contains utilities related to Android developement 
-# but to to setting up the environnment and working with the Platfom. 
+# This file contains utilities related to Android developement
+# but to to setting up the environnment and working with the Platfom.
 # android_env is the file containing environmment related function
 
 # Edit this file
@@ -12,32 +12,33 @@ alias pidcat=~/.dotfiles/android/pidcat.py
 function adbd() {
     # Prompt which device to use before running the adb command
     local filter=""
-    if [[ "$1" == "-f" ]] ; then
-        shift;
-        filter="$1"; shift
+    if [[ "$1" == "-f" ]]; then
+        shift
+        filter="$1"
+        shift
     fi
 
     local devices=$(adb devices -l | awk '{print $1 "\t" $4 "\t" $5}')
     header="$devices"
     devices=$(echo "$devices" | tail -n +2)
-    count=$(( $(echo "$devices" | wc -l) - 1 ))
+    count=$(($(echo "$devices" | wc -l) - 1))
     sel=1
     serial=-1
-    if [[ -n $filter ]] ; then
+    if [[ -n $filter ]]; then
         serial=$(echo "$devices" | grep "$filter" | awk '{print$1}')
     else
-        if [ $count -gt 1 ] ; then
-            echo $( echo "$header" | head -n1 ) >&2
+        if [ $count -gt 1 ]; then
+            echo $(echo "$header" | head -n1) >&2
             echo "$devices" | >&2 grep -n '^'
             read sel"?Device: "
         fi
-        if [[ -z $sel  ]] ; then
-            return 0;
+        if [[ -z $sel ]]; then
+            return 0
         fi
         serial=$(echo "$devices" | awk "NR==$sel {print\$1}")
     fi
 
-    if [ $#  -gt 0 ] ; then
+    if [ $# -gt 0 ]; then
         adb -s "$serial" "$@"
     else
         echo "$serial"
@@ -46,20 +47,22 @@ function adbd() {
 
 function adba() {
     local filter=""
-    if  [[ "$1" = "-f" ]] ; then
-        filter="$2"; shift; shift;
+    if [[ "$1" = "-f" ]]; then
+        filter="$2"
+        shift
+        shift
     fi
 
-    if [[ $# -lt 1 ]] ; then 
-      echo "No args given for ADB";
-       return 1; 
+    if [[ $# -lt 1 ]]; then
+        echo "No args given for ADB"
+        return 1
     fi
 
     devices=$(adb devices -l | tail -n+2)
     [[ -n $filter ]] && devices=$(echo "$devices" | grep "$filter")
     echo "$devices"
-    echo "$devices" | while read current ; do
-        if [[ -n $current ]] ; then
+    echo "$devices" | while read current; do
+        if [[ -n $current ]]; then
             echo "$current"
             serial=$(echo "$current" | awk '{print$1}')
             adb </dev/null -s "$serial" "$@"
@@ -73,14 +76,17 @@ function adbk() {
     [[ -z $processes ]] && return
     ports=$(echo "$processes" | awk '{if ($5) print$5}')
     [[ -z $ports ]] && ports="5037"
-    echo $ports | while read port; do 
+    echo $ports | while read port; do
         echo "Killing server on port $port"
         adb -P "$port" kill-server
     done
 
-    sleep 1;
+    sleep 1
     processids=$(pgrep adb | awk '{print$1}')
-    [[ -z $processids ]] && {  echo "All ADB servers killed"; return; }
+    [[ -z $processids ]] && {
+        echo "All ADB servers killed"
+        return
+    }
     echo "$processids" | while read pid; do
         echo "Killing leftover adb process $pid"
         kill -9 "$pid"
@@ -88,18 +94,21 @@ function adbk() {
 }
 
 function avd() {
-    local id;
+    local id
 
     # List the available AVD, and prompt which one to use
     avds=$(emulator -list-avds)
     [[ -z $avds ]] && return 1
     echo "$avds"
-    read -r "a?AVD:";
+    read -r "a?AVD:"
     echo
     [[ -z $a ]] && return
     id=$(echo "$avds" | grep "$a")
-    [[ -z $id ]] && { echo "No AVD matching $a. Aborting."; return 1; }
-    if [[ $(echo "$id" | wc -l) -gt 1 ]] ; then
+    [[ -z $id ]] && {
+        echo "No AVD matching $a. Aborting."
+        return 1
+    }
+    if [[ $(echo "$id" | wc -l) -gt 1 ]]; then
         echo "$id"
         echo "More than one device mathing $id. Aborting."
         return 1
@@ -127,48 +136,51 @@ function ash {
 
 alias aa=adbserial
 function adbserial() {
-    # Show a list the available device to select and set to the ANDROID_SERIAL 
+    # Show a list the available device to select and set to the ANDROID_SERIAL
     # variable.
     # If an argument is given, the line matching the argument will be used without
     # showing a prompt.
     local filter=""
     local fastboot
     local use_pontis
-    while [[ $# -gt 0 ]] ; do
+    while [[ $# -gt 0 ]]; do
         case $1 in
-            -h)
-                echo "Usage: fastboot [flags] [filter]\n \
+        -h)
+            echo "Usage: fastboot [flags] [filter]\n \
 flags:
     -h : help.\n\
     -f : fastboot.\n\
     -p : use pontis."
-                return 0
-                ;;
-            -f)
-                fastboot=true; shift;
-                ;;
-            -p) 
-                use_pontis=true; shift;
-                ;;
-            *)
-                filter="-f $1"; shift
-                ;;     
+            return 0
+            ;;
+        -f)
+            fastboot=true
+            shift
+            ;;
+        -p)
+            use_pontis=true
+            shift
+            ;;
+        *)
+            filter="-f $1"
+            shift
+            ;;
         esac
     done
 
-    if [[ $use_pontis == true ]] ; then
-        if [[ $fastboot == true ]] ; then
-            serial=$(pontis devices | grep fastboot |  fzf --height=5 | awk '{print$2}')
+    if [[ $use_pontis == true ]]; then
+        if [[ $fastboot == true ]]; then
+            serial=$(pontis devices | grep fastboot | fzf --height=5 | awk '{print$2}')
         else
-            serial="$(pontis devices | grep ADB | fzf --height=5 | awk '{print$6}' )"
+            serial="$(pontis devices | grep ADB | fzf --height=5 | awk '{print$6}')"
             [[ -n $serial ]] && serial=localhost:$serial
         fi
     else
         local serial
         serial=$(adbd $(echo "$filter"))
     fi
-    
-    if [[ -z $serial ]] ; then
+
+    if [[ -z $serial ]]; then
         unset ANDROID_SERIAL
         unset ANDROID_SERIAL_PRODUCT
     else
@@ -189,17 +201,17 @@ function adbsync() {
 
 function apxtodp {
     # Convert px to dp for the connected device
-    [[ -z $1 ]] && return 1;
+    [[ -z $1 ]] && return 1
     density=$(adb shell wm density | cut -d':' -f2)
-    (( res = ($1 * 160 ) /  $density ));
+    ((res = ($1 * 160) / $density))
     echo $res
 }
 
 function adptopx {
     # Convert dp to px for the connected device
-    [[ -z $1 ]] && return 1;
+    [[ -z $1 ]] && return 1
     density=$(adb shell wm density | cut -d':' -f2)
-    (( px = ($1 * $density ) /  160.0 ));
+    ((px = ($1 * $density) / 160.0))
     echo $px
 }
 
@@ -219,20 +231,19 @@ function adebugapp() {
     # -p for --persitent
 
     local persitent=
-    if [[ $1 == "-p" ]] ; then
+    if [[ $1 == "-p" ]]; then
         persitent="--persistent"
         shift
     fi
 
-
-    local pkgs;
-    if [[ -z $1 ]] ; then
-	    pkgs=$(apkg)
+    local pkgs
+    if [[ -z $1 ]]; then
+        pkgs=$(apkg)
     else
         pkgs=$(adb shell pm list packages -3 --user 0 | grep $1 | cut -f2 -d':')
     fi
 
-    if [[ `echo $pkgs | wc -l` != 1 ]] ; then
+    if [[ $(echo $pkgs | wc -l) != 1 ]]; then
         echo "0 or more than 1 package mathing $1"
         echo $pkgs
         return 1
@@ -243,7 +254,7 @@ function adebugapp() {
 }
 
 function apic {
-    local filename=screen-$(date  "+%Y%m%d_%H-%M-%S").png
+    local filename=screen-$(date "+%Y%m%d_%H-%M-%S").png
     local out="/storage/emulated/0/Pictures/Screenshots/$filename"
     adb shell screencap "$out"
     adlpic ~/D/
@@ -253,10 +264,14 @@ function apic {
 
 function adll {
     # Download the latest file in the provided folder
-    [[ $1 == "-h" ]] && { echo """Download the latest file in the folder"""; return 0; }
-    dir="$1"; shift
+    [[ $1 == "-h" ]] && {
+        echo """Download the latest file in the folder"""
+        return 0
+    }
+    dir="$1"
+    shift
     local out=""
-    if [[ -n $1 ]] ; then
+    if [[ -n $1 ]]; then
         out="$1"
     else
         out="./"
@@ -266,7 +281,7 @@ function adll {
 
 function astopstart() {
     # Restart the system server
-    adb shell stop && adb shell start;
+    adb shell stop && adb shell start
 }
 
 function aps() {
@@ -274,40 +289,73 @@ function aps() {
     grep_str=""
     pid=false
     verbose=false
-    [[ "$1" == "-p" ]] && { pid=true; shift; }
-    [[ "$1" == "-v" ]] && { verbose=true; shift; }
+    [[ "$1" == "-p" ]] && {
+        pid=true
+        shift
+    }
+    [[ "$1" == "-v" ]] && {
+        verbose=true
+        shift
+    }
     [[ -n "$1" ]] && grep_str="$1"
 
-    if [[ -z $grep_str ]] ; then
+    if [[ -z $grep_str ]]; then
         local awk_index=9
-        if [[ $pid == true ]] ; then 
+        if [[ $pid == true ]]; then
             awk_index=2
         fi
-        adb shell ps | fzf --header-lines 1 --layout=reverse --height=30%  --multi --exact | awk "{print\$$awk_index}"
-        return 0;
+        adb shell ps | fzf --header-lines 1 --layout=reverse --height=30% --multi --exact | awk "{print\$$awk_index}"
+        return 0
     fi
-    if [[ $verbose == true ]] ; then 
+    if [[ $verbose == true ]]; then
         adb shell ps -o pid -o name | grep "$grep_str"
-    elif [[ $pid == true ]] ; then 
+    elif [[ $pid == true ]]; then
         adb shell ps -o name -o pid | grep "$grep_str" | awk '{print$2}'
-    elif [[ -n $grep_str ]] ; then
+    elif [[ -n $grep_str ]]; then
         adb shell ps -o name | grep "$grep_str"
     fi
 }
 
 function apkg() {
-	# List installed package and their uid
-	adb shell pm list package -U "$@" | \
-		sed 's/\(package\|uid\)://gi' | \
-		column -t -N "PACKAGE, UID"   | \
-		fzf --header-lines 1 --reverse --height 20 | \
-		awk '{print$1}'
+    # List installed package and their uid
+    local packages=$(adb shell pm list package -U "$1" | sed 's/\(package\|uid\)://gi')
+    if [[ $(echo $packages | wc -l) -eq 1 ]]; then
+        echo $packages | awk '{print$1}'
+        return 0
+    fi
+
+    echo $packages | column -t -N "PACKAGE, UID" | fzf --header-lines 1 --reverse --height 20 |
+        awk '{print$1}'
 }
 
 function akill() {
     # Kill android processes
-    processes=$(aps -p)
-    [[ -n $processes ]] && adb shell kill "$@" $(echo $processes)
+    local positionals=()
+    local filter=()
+    while [[ -n $1 ]]; do
+        case $1 in
+        -*)
+            positionals+=($1)
+            shift
+            ;;
+        *)
+            filter+=($1)
+            shift
+            ;;
+        esac
+    done
+    processes=$(aps -p ${filter[@]})
+    [[ -n $processes ]] && adb shell kill "${positionals[@]}" $(echo $processes)
+}
+
+function amstart() {
+    # Pick and start an activity
+    pkg=$(apkg "$@")
+    [[ -n $pkg ]] || return 1
+    activity=$(adb shell dumpsys package | grep "$pkg/" | awk '{print$2}' | sort -u | fzf --select-1 --query="$*")
+    [[ -n $activity ]] || return 1
+    echo "adb shell am start -S -n $activity"
+    adb shell am start -S -n "$activity"
 }
 
 function atouch {
@@ -334,27 +382,29 @@ function ascreen {
     dir="/storage/emulated/0/Movies"
     recording=
 
-    while [[ -n $1 ]] ; do 
+    while [[ -n $1 ]]; do
         case $1 in
-            -d)
-                out=$2;
-                [[ -d $out ]] || return 1
-                shift; shift
-                ;;
-            -f)
-                filename="$2.mp4"
-                shift; shift
-                ;;
+        -d)
+            out=$2
+            [[ -d $out ]] || return 1
+            shift
+            shift
+            ;;
+        -f)
+            filename="$2.mp4"
+            shift
+            shift
+            ;;
         esac
     done
-    
-    [[ -z $filename ]] && filename="screen-$(date  "+%Y%m%d_%H-%M-%S").mp4"
+
+    [[ -z $filename ]] && filename="screen-$(date "+%Y%m%d_%H-%M-%S").mp4"
     file="$dir/$filename"
 
     TRAPINT() {
         recording=
         unfunction TRAPINT
-        if [[ $screen_record_pid -gt 0 ]] ; then
+        if [[ $screen_record_pid -gt 0 ]]; then
             kill -INT $screen_record_pid
         fi
         sleep 0.5
@@ -365,7 +415,7 @@ function ascreen {
 
     # enable touches
     adb shell content insert --uri content://settings/system --bind name:s:show_touches --bind value:i:1
-    
+
     echo "Starting recording on device"
     recording="true"
     adb shell "screenrecord $file"
@@ -378,43 +428,43 @@ function logcat() {
     local format="brief time color"
     local args=()
     local positionals=()
-    while [[ -n $1 ]] ; do
+    while [[ -n $1 ]]; do
         case $1 in
-            error)
-                args+=("*:E")
-                shift
-                ;;
-            warn)
-                args+=("*:W")
-                shift
-                ;;
-            debug)
-                args+=("*:D")
-                shift
-                ;;
-            all)
-                args+=(-b all)
-                shift
-                ;;
-            -c)
-                adb logcat -c && echo "Logcat cleared"
-                return
-                ;;
-            *)
-	            positionals+=($1)
-		        shift
-        		;;
+        error)
+            args+=("*:E")
+            shift
+            ;;
+        warn)
+            args+=("*:W")
+            shift
+            ;;
+        debug)
+            args+=("*:D")
+            shift
+            ;;
+        all)
+            args+=(-b all)
+            shift
+            ;;
+        -c)
+            adb logcat -c && echo "Logcat cleared"
+            return
+            ;;
+        *)
+            positionals+=($1)
+            shift
+            ;;
         esac
     done
-    logcat_outfile=$(mktemp --tmpdir logcat-`date "+%Y-%m-%d_%H-%M-%S"`-XXX.log)
+    logcat_outfile=$(mktemp --tmpdir logcat-$(date "+%Y-%m-%d_%H-%M-%S")-XXX.log)
     echo "Saving to \$logcat_outfile $logcat_outfile" >&2
-    adb logcat -v "$format" "${args[@]}" "${positionals[@]}" | tee $logcat_outfile |  less --ignore-case --quit-if-one-screen -R +F 
+    adb logcat -v "$format" "${args[@]}" "${positionals[@]}" | tee $logcat_outfile | less --ignore-case --quit-if-one-screen -R +F
 }
 
 function adebugenable() {
     # Enable JDWP debugging
-	adb shell setprop persist.debug.dalvik.vm.jdwp.enabled 1
-	adb reboot
+    adb shell setprop persist.debug.dalvik.vm.jdwp.enabled 1
+    adb reboot
 }
 
 function sjava() {
@@ -447,7 +497,8 @@ function aanr() {
 }
 
 function aselinuxaudit() {
-    adb pull /sys/fs/selinux/policy; adb logcat -b events -d | audit2allow -p policy
+    adb pull /sys/fs/selinux/policy
+    adb logcat -b events -d | audit2allow -p policy
 }
 
 function android_generate_compile_commands() {
